// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyATDYRZVG5yCOQxVzqtH4n0Oq1a_dxOcX0',
    appId: '1:437874551355:web:fb0218c077a2b8e1c80a1e',
    messagingSenderId: '437874551355',
    projectId: 'scorescope-5a12b',
    authDomain: 'scorescope-5a12b.firebaseapp.com',
    storageBucket: 'scorescope-5a12b.firebasestorage.app',
    measurementId: 'G-P0WTZQ1HWC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBwIrIscOSlFZy_bcmGyxpctvZywwJq_RE',
    appId: '1:437874551355:android:747a62c5854af83cc80a1e',
    messagingSenderId: '437874551355',
    projectId: 'scorescope-5a12b',
    storageBucket: 'scorescope-5a12b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBcfstBH5wBP-eEBKeRAyPFE43CJil7WFY',
    appId: '1:437874551355:ios:870ed21e70dd1171c80a1e',
    messagingSenderId: '437874551355',
    projectId: 'scorescope-5a12b',
    storageBucket: 'scorescope-5a12b.firebasestorage.app',
    iosClientId: '437874551355-otkgka35uq341a2fmjg189us6qs655cm.apps.googleusercontent.com',
    iosBundleId: 'com.example.scorescope',
  );
}
